### ISSUE TITLE
Chinese analysis problem

### ISSUE THREAD

**Issue by kwangin** [ikegami-yukino/rakutenma-python#4]
Hello.
I just ran a simple lines like this, but it does not shows good results like demo page.

```
from rakutenma import RakutenMA


rma = RakutenMA()
rma.load("model_zh.min.json")

print(rma.tokenize("我把我的成功归功于他。"))
```
=>
```
[['我把我的成功归功', 'VV'], ['于', 'NR'], ['他', ''], ['。', '']]
```

Is there something more I have to do?

**Comment by ikegami-yukino** [comment]
Hmm...

We can set the featset as following:
```
rma.featset = rakutenma.FEATSET_ZH
```
Nevertheless, same results are got.

Please correct by `rma.train_one` method.

**Comment by kination** [comment]
How can I correct with rma.train_one? Do I have to do like below?
```
import json
zh = json.load(open("model_zh.json"))
for i in zh:
    rma.train_one(i)
```
This cause bug like below.
```
Traceback (most recent call last):
  File "analyzer.py", line 13, in <module>
    rma.train_one(i)
  File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/site-packages/rakutenma/rakutenma.py", line 528, in train_one
    ans_csent = self.tokens2csent(sent, self.tag_scheme)
  File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/site-packages/rakutenma/rakutenma.py", line 472, in tokens2csent
    l="S-" + token[1]))
IndexError: string index out of range
```

**Comment by ikegami-yukino** [comment]
Sorry.
This is a bug.
I'll fix it.

**Comment by kination** [comment]
@ikegami-yukino Thanks!

**Comment by ikegami-yukino** [comment]
@djKooks 
rakutenma-python is updated.
Please try it.

**Comment by kination** [comment]
@ikegami-yukino Thanks! I'll look on it.

**Comment by kination** [comment]
It does not cause error, but result is not good yet.
This is my full code.
```
from rakutenma import RakutenMA, FEATSET_ZH
import json


rma = RakutenMA()
rma.featset = FEATSET_ZH
zh = json.load(open("model_zh.json"))
for i in zh:
    rma.train_one(i)

print(rma.tokenize('我把我的成功归功于他。'))
```
And result is
```
[['我', ''], ['把', ''], ['我', ''], ['的', ''], ['成', ''], ['功', ''], ['归', ''], ['功', ''], ['于', ''], ['他', ''], ['。', '']]
```

**Comment by ikegami-yukino** [comment]
The `train_one` method requires list of [word, part-of-speech] pair.
i.e. Using `train_one` is such as following:

```python
from rakutenma import RakutenMA, FEATSET_ZH

rma = RakutenMA()
rma.load("model_zh.json")
rma.featset = FEATSET_ZH
rma.set_tag_scheme("IOB2")

for pair in [[u'我', u'PN']]:
    rma.train_one(pair)
```

**Comment by kination** [comment]
@ikegami-yukino Oh, got it. Thanks!
